spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datastream
    username: postgres
    password: postgres

services:
  paystack:
    apiKey: sk_test_ae623994037cb18b4406d479af6c2ed461840bb9

  biller:
    apiKey: b5zPWjbkDAvj/8fVV/EHvmu20SM9gb9Z98uRXLrA+jY=
