spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datastream
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

services:
  paystack:
    baseUrl: https://api.paystack.co
    apiKey: sk_test_ae623994037cb18b4406d479af6c2ed461840bb9
    callbackUrl: ""

  biller:
    baseUrl: https://api.staging.baxibap.com
    apiKey: b5zPWjbkDAvj/8fVV/EHvmu20SM9gb9Z98uRXLrA+jY=


schedulers:
  electricity:
      cron: "* */10 * * * ?"
      fixedDelay: 43200000
      initialDelay: 1000