spring:
  datasource:
    url: jdbc:postgresql://localhost:55000/datastream
    username: postgres
    password: postgrespw


services:
  paystack:
    apiKey: ""

  biller:
    apiKey: "b5zPWjbkDAvj/8fVV/EHvmu20SM9gb9Z98uRXLrA+jY="

