spring:
  datasource:
    url: jdbc:postgresql://localhost:5041/dataStream
    username: postgres
    password: password


services:
  paystack:
    apiKey: ""

  biller:
    apiKey: "b5zPWjbkDAvj/8fVV/EHvmu20SM9gb9Z98uRXLrA+jY="
